# Setup
title:               degregat
tagline:             ''
description:         'Applied Mechanism Design, Privacy Preserving Machine Learning, Distributed Systems'
url:                 https://degregat.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             ghpublic@degregat.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
